#!/bin/bash

# Copyright (C) 2022-2023 Steve Jeong <steve@how2flow.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

get_wpi() {
  local phy_to_wpi=('x' 'x' 'x' 8 'x' 9 'x' 7 15 'x' 16 0 1 2 'x' 3 4 'x' 5 12 'x' 13 6 14 10 'x' 11 30 31 21 'x' 22 26 23 'x' 24 27 'x' 'x' 'x' 'x')

  echo "${phy_to_wpi[$1]}"
}

usage() {
  echo "Usage: wiringpi-test [TARGET]"
  echo ""
  echo "It is the pin test package with wiringpi"
  echo "-i, --i2c [BUS (defualt: 0)]      test i2c with wiringpi"
  echo "-s, --spi [CS (defualt: 0)]       test spi with wiringpi"
  echo "-g, --gpio                        test gpio with wiringpi"
}
